teams:
  - name: agora-glass-pumpkin-maintainers
    maintainers:
      - mikelodder7
  - name: agora-lab-admins
    maintainers:
      - mikelodder7
  - name: agora-key-share-proofs-maintainers
    maintainers:
      - mikelodder7
    members:
      - nglaeser
  - name: aries-bbs-maintainers
    maintainers:
      - andrewwhitehead
      - swcurran
    members:
      - WadeBarnes
      - mikelodder7
  - name: aries-labs-maintainers
    maintainers:
      - conanoc
    members:
      - TheTreek
  - name: artizyou-maintainers
    maintainers:
      - MuhammadRizwanMughal
    members:
      - SamDrissi
      - rgagnon
  - name: bots
    maintainers:
      - lfdt-bot
  - name: cbweb3-maintainers
    maintainers:
      - carolacnet
    members:
      - BernardoPaniaguaCEMLA
      - JulioRodB
      - MaxMitre
      - jferreira9620
      - leninortiz
      - nayamhb
      - Andres-BCRD
      - jushua
      - HChitman
      - camposmm-mar
      - betoencinas
      - josegabrielsv
      - lddia
      - sergiobcrd
      - markymark021282
      - samuelvenzi
      - LFJeronymo
      - andremacedopv
      - lucas-campelo
      - goledger
      - lukasjhan
      - aceshim
      - Jymmbo
      - alvaroacev
      - robertomorenoallien
      - rafael-nuam
      - yuricarrillo-wq
      - linaparral
      - YennyReina
      - adcjc
  - name: chaindeploy-maintainers
    maintainers:
      - dviejokfs
  - name: decentralized-directory-protocol-maintainers
    maintainers:
      - amarts
    members:
      - pramodkvarma
      - surendrasinghs
  - name: fabino-test-maintainers
    maintainers:
      - aminchegeni
  - name: fabric-x-ansible-collection-maintainers
    maintainers:
      - iliecirciumaru
    members:
      - pasquale95
  - name: fabric-x-block-explorer-committers
    maintainers:
      - farooqazamwasimnl
      - liran-funaro
      - cendhu
  - name: fabric-rust-maintainers
    maintainers:
      - arne-fuchs
  - name: flavum-maintainers
    maintainers:
      - Daniel-Szego
  - name: gitmesh-committers
    maintainers:
      - RAWx18
    members:
      - Parvm1102
      - Ronit-Raj9
  - name: hypernate-maintainers
    maintainers:
      - aklenik
    members:
      - bzp99
  - name: hoprs-maintainers
    maintainers:
      - mattnbrown
    members:
      - Henrikcox
  - name: identity-bot-maintainers
    maintainers:
      - bobert600
    members:
      - chemerisuk
  - name: lab-stewards
    maintainers:
      - mbrandenburger
    members:
      - alvaropicazo
      - arsulegai
      - dmueller2001
      - EnriqueL8
      - hendrikebbers
      - kkaur01
      - kmillikin
      - matthew1001
      - OsamaRab3
      - tock-ibm
      - VRamakrishna
  - name: opendecentra-nextg-maintainers
    maintainers:
      - Rudrakshrawal
  - name: openvtc-maintainers
    maintainers:
      - stormer78
  - name: security-managers
    maintainers:
      - ryjones
    members:
      - hartm
      - jwagantall
  - name: naryo-maintainers
    maintainers:
      - romangzz
      - adovale-IOB
      - IvanSaizIOB
    members:
      - marcosio
      - ppolo23
      - lfrKain
      - SergioIOB
      - franpersanchez
      - mtxasko
  - name: one-attestation-api-maintainers
    maintainers:
      - bvavala
  - name: verazt-committers
    maintainers:
      - taquangtrung
    members:
      - cassc
      - minhhn2910
      - ooibc
      - xkxiao
  - name: waterfall-committers
    maintainers:
      - on-waterfall
  - name: zkbk-committers
    maintainers:
      - rsinha
    members:
      - Arka19
      - guruvamsi-policharla
      - hartm
      - keewoolee
      - sanjamg
  - name: zk-learning-group-committers
    maintainers:
      - Daniel-Szego
  - name: zkproof-polycommit-committers
    maintainers:
      - therealyingtong
repositories:
  - name: agora-allosaurus-rs
    teams:
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-bbs
    teams:
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-blsful
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-glass_pumpkin
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-key-share-proofs
    teams:
      agora-key-share-proofs-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-unknown_order
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-verifiable-encryption
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: aries-bbssignatures-rs
    teams:
      aries-bbs-maintainers: maintain
      security-managers: read
    visibility: public
  - name: aries-framework-kotlin
    teams:
      aries-labs-maintainers: maintain
      security-managers: read
    visibility: public
  - name: aries-framework-swift
    teams:
      aries-labs-maintainers: maintain
      security-managers: read
    visibility: public
  - name: aries-uniffi-wrappers
    teams:
      aries-labs-maintainers: maintain
      security-managers: read
    visibility: public
  - name: artizyou
    teams:
      artizyou-maintainers: maintain
      security-managers: read
    visibility: public
  - name: cbweb3
    teams:
      cbweb3-maintainers: maintain
      security-managers: read
    visibility: public
  - name: chaindeploy
    teams:
      bots: maintain
      chaindeploy-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: decentralized-directory-protocol
    teams:
      bots: maintain
      decentralized-directory-protocol-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: fabino-test
    teams:
      bots: maintain
      fabino-test-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: fabric-x-ansible-collection
    teams:
      bots: maintain
      fabric-x-ansible-collection-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: fabric-x-block-explorer
    teams:
      fabric-x-block-explorer-committers: maintain
      security-managers: read
    visibility: public
  - name: fabric-sdk-rust
    teams:
      bots: maintain
      fabric-rust-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: fabric-chaincode-rust
    teams:
      bots: maintain
      fabric-rust-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: flavum
    teams:
      bots: maintain
      flavum-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: gitmesh
    teams:
      bots: maintain
      gitmesh-committers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: HOPrS
    teams:
      bots: maintain
      hoprs-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: hypernate
    teams:
      bots: maintain
      hypernate-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: hypernate-samples
    teams:
      bots: maintain
      hypernate-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: identity-bot
    teams:
      bots: maintain
      identity-bot-maintainers: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: governance
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: LF-Decentralized-Trust-labs.github.io
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: Naryo
    teams:
      bots: maintain
      lab-stewards: maintain
      naryo-maintainers: maintain
      security-managers: read
    visibility: public
  - name: one-attestation-api
    teams:
      bots: maintain
      lab-stewards: maintain
      one-attestation-api-maintainers: maintain
      security-managers: read
    visibility: public
  - name: opendecentra-nextg
    teams:
      bots: maintain
      lab-stewards: maintain
      opendecentra-nextg-maintainers: maintain
      security-managers: read
    visibility: public
  - name: verifiable-trust-infrastructure
    teams:
      bots: maintain
      lab-stewards: maintain
      openvtc-maintainers: maintain
      security-managers: read
    visibility: public
  - name: dtg-credentials
    teams:
      bots: maintain
      lab-stewards: maintain
      openvtc-maintainers: maintain
      security-managers: read
    visibility: public
  - name: openvtc
    teams:
      bots: maintain
      lab-stewards: maintain
      openvtc-maintainers: maintain
      security-managers: read
    visibility: public
  - name: verazt
    teams:
      bots: admin
      security-managers: read
      verazt-committers: write
    visibility: public
  - name: waterfall-coordinator
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-docs
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-gwat
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-one-click-setup-app
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: zkbk
    teams:
      bots: admin
      security-managers: read
      zkbk-committers: maintain
    visibility: public
  - name: zk-learning-group
    teams:
      bots: admin
      security-managers: read
      zk-learning-group-committers: maintain
    visibility: public
  - name: zkproof-polycommit
    teams:
      bots: admin
      security-managers: read
      zkproof-polycommit-committers: maintain
    visibility: public
